using Content.Shared.Sich.BureaucraticComputer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System;
using System.Text.RegularExpressions;

namespace Content.Client.Sich.BureaucraticComputer.UI;

[GenerateTypedNameReferences]
public sealed partial class BureaucracyComputerWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public readonly Dictionary<string, TextEdit> InputControls = new();

    public Action<BureaucraticDocumentPrototype>? OnDocumentSelected;
    public Action<string, Dictionary<string, string>>? OnPrintPressed;
    private ProtoId<BureaucraticDocumentPrototype>? _selectedDocumentId;


    public Regex FieldRegex = SharedBureacraticComputerSystem.FieldRegex;

    public BureaucracyComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateDocuments();

        // Обробник натискання кнопки друку
        PrintButton.OnPressed += _ =>
        {
            if (_selectedDocumentId == null)
                return;

            var filledData = new Dictionary<string, string>();
            foreach (var (key, textEdit) in InputControls)
            {
                filledData[key] = Rope.Collapse(textEdit.TextRope) ?? string.Empty;
            }

            OnPrintPressed?.Invoke(_selectedDocumentId, filledData);
        };
    }

    private void PopulateDocuments()
    {
        foreach (var document in _prototypeManager.EnumeratePrototypes<BureaucraticDocumentPrototype>())
        {
            var button = new Button
            {
                Text = document.Name
            };

            button.OnPressed += _ =>
            {
                OnDocumentSelected?.Invoke(document);
                GenerateFields(document);
            };

            DocumentList.AddChild(button);
        }
    }

    private void GenerateFields(BureaucraticDocumentPrototype document)
    {
        DocumentFields.DisposeAllChildren();
        InputControls.Clear();

        _selectedDocumentId = document.ID;
        PrintButton.Disabled = false;

        var matches = FieldRegex.Matches(document.Text);
        var processedFields = new HashSet<string>();

        foreach (Match match in matches)
        {
            var fieldName = match.Groups[1].Value;

            if (!processedFields.Add(fieldName))
                continue;

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical
            };

            var label = new Label
            {
                Text = fieldName + ":",
                FontColorOverride = Color.FromHex("#A3A3A3"), // Світло-сірий колір для назв полів
                Margin = new Thickness(0, 0, 0, 4)
            };

            // Створюємо "коробку" для поля вводу, щоб воно не виглядало як порожнеча
            var textEditBackground = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1B1B1B") }, // Темний фон
                HorizontalExpand = true
            };

            var textEdit = new TextEdit
            {
                HorizontalExpand = true,
                MinHeight = 35,
                Margin = new Thickness(5) // Внутрішній відступ тексту від країв "коробки"
            };

            textEdit.OnTextChanged += args =>
            {
                var text = Rope.Collapse(args.Control.TextRope) ?? string.Empty;
                var lineCount = text.Split('\n').Length;
                // Адаптуємо висоту самої коробки вводу
                args.Control.MinHeight = Math.Max(35, lineCount * 20 + 15);
            };

            textEditBackground.AddChild(textEdit);

            container.AddChild(label);
            container.AddChild(textEditBackground);

            DocumentFields.AddChild(container);
            InputControls.Add(fieldName, textEdit);
        }
    }
}
