using Content.Client.UserInterface.Controls;
using Content.Shared.Sich.BureaucraticComputer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System;
using System.Text.RegularExpressions;
namespace Content.Client.Sich.BureaucraticComputer.UI;

[GenerateTypedNameReferences]
public sealed partial class BureaucracyComputerWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public readonly Dictionary<string, TextEdit> InputControls = new();

    public Action<BureaucraticDocumentPrototype>? OnDocumentSelected;
    public Action<string, Dictionary<string, string>>? OnPrintPressed;
    private ProtoId<BureaucraticDocumentPrototype>? _selectedDocumentId;


    public Regex FieldRegex = SharedBureacraticComputerSystem.FieldRegex;

    public BureaucracyComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var panelBg = new StyleBoxFlat { BackgroundColor = Color.FromHex("#1B1B1B") };
        LeftBackgroundPanel.PanelOverride = panelBg;
        RightBackgroundPanel.PanelOverride = panelBg;

        PopulateDocuments();

        PrintButton.OnPressed += _ =>
        {
            if (_selectedDocumentId == null)
                return;

            var filledData = new Dictionary<string, string>();
            foreach (var (key, textEdit) in InputControls)
            {
                filledData[key] = Rope.Collapse(textEdit.TextRope) ?? string.Empty;
            }

            OnPrintPressed?.Invoke(_selectedDocumentId, filledData);
        };
    }

    private void PopulateDocuments()
    {
        foreach (var document in _prototypeManager.EnumeratePrototypes<BureaucraticDocumentPrototype>())
        {
            var button = new Button
            {
                Text = document.Name
            };

            button.OnPressed += _ =>
            {
                OnDocumentSelected?.Invoke(document);
                GenerateFields(document);
            };

            DocumentList.AddChild(button);
        }
    }

    private void GenerateFields(BureaucraticDocumentPrototype document)
    {
        DocumentFields.DisposeAllChildren();
        InputControls.Clear();

        _selectedDocumentId = document.ID;
        PrintButton.Disabled = false;

        // 1. Додаємо назву обраного документу зверху списку полів
        var documentTitle = new Label
        {
            Text = document.Name,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.FromHex("#5E9CFF"), // Приємний синій колір для виділення
            Margin = new Thickness(0, 0, 0, 20) // Робимо більший відступ знизу
        };
        documentTitle.StyleClasses.Add("LabelHeading"); // Робимо шрифт більшим (як у заголовків)
        DocumentFields.AddChild(documentTitle);

        var matches = FieldRegex.Matches(document.Text);
        var processedFields = new HashSet<string>();

        foreach (Match match in matches)
        {
            var fieldName = match.Groups[1].Value;

            if (!processedFields.Add(fieldName))
                continue;

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 10) // Відступ між окремими полями
            };

            // 2. Робимо заголовки полів виразнішими
            var label = new Label
            {
                Text = $"▶ {fieldName.ToUpper()}:", // Додаємо стрілочку і робимо великими літерами
                FontColorOverride = Color.FromHex("#EAEAEA"), // Яскраво-білий/світло-сірий колір
                Margin = new Thickness(0, 0, 0, 4)
            };
            label.StyleClasses.Add("LabelKeyText"); // Додаємо стандартний стиль SS14 для жирного тексту

            var textEditBackground = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2C2C34") },
                HorizontalExpand = true
            };

            var textEdit = new TextEdit
            {
                HorizontalExpand = true,
                MinHeight = 35,
                Margin = new Thickness(5)
            };

            textEdit.OnTextChanged += args =>
            {
                var text = Rope.Collapse(args.Control.TextRope) ?? string.Empty;
                var lineCount = text.Split('\n').Length;
                args.Control.MinHeight = Math.Max(35, lineCount * 20 + 15);
            };

            textEditBackground.AddChild(textEdit);

            container.AddChild(label);
            container.AddChild(textEditBackground);

            DocumentFields.AddChild(container);
            InputControls.Add(fieldName, textEdit);
        }
    }
}
