using Content.Client.Paper.UI;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using System;
using System.Numerics;

namespace Content.Client.Photography.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PalaroidWindow : BaseWindow
    {
        [Dependency] private readonly IInputManager _inputManager = default!;
        [Dependency] private readonly IResourceCache _resCache = default!;

        private static Color DefaultTextColor = new(25, 25, 25);
        private const int DRAG_MARGIN_SIZE = 16;
        private DragMode _allowedResizeModes = ~DragMode.None;

        public event Action<string>? OnSaved;

        private int _MaxInputLength = -1;
        public int MaxInputLength
        {
            get => _MaxInputLength;
            set
            {
                _MaxInputLength = value;
                UpdateFillState();
            }
        }

        public PalaroidWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            CloseButton.OnPressed += _ => Close();

            Input.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.MultilineTextSubmit)
                {
                    if (!SaveButton.Disabled)
                    {
                        RunOnSaved();
                        args.Handle();
                    }
                }
            };

            Input.OnTextChanged += _ => UpdateFillState();

            SaveButton.OnPressed += _ => RunOnSaved();

            SaveButton.Text = Loc.GetString("paper-ui-save-button",
                ("keybind", _inputManager.GetKeyFunctionButtonString(EngineKeyFunctions.MultilineTextSubmit)));
        }

        public void SetPhoto(string photoRichText)
        {
            if (string.IsNullOrEmpty(photoRichText))
                return;

            var msg = new FormattedMessage();
            msg.AddMarkupPermissive(photoRichText);
            PolaroidImage.SetMessage(msg, null, null);
        }

        public void Populate(PaperComponent.PaperBoundUserInterfaceState state)
        {
            bool isEditing = state.Mode == PaperComponent.PaperAction.Write;

            InputContainer.Visible = isEditing;
            SaveButton.Visible = isEditing;
            EditButtons.Visible = isEditing;

            var msg = new FormattedMessage();
            msg.AddMarkupPermissive(state.Text);
            WrittenTextLabel.SetMessage(msg, null, DefaultTextColor);

            WrittenTextLabel.Visible = !isEditing && !string.IsNullOrWhiteSpace(state.Text);

            if (isEditing && Input.TextLength == 0 && !string.IsNullOrEmpty(state.Text))
            {
                Input.TextRope = Rope.Leaf.Empty;
                Input.InsertAtCursor(state.Text);
            }
        }

        public void InitVisuals(PaperVisualsComponent visuals)
        {
            PaperBackground.ModulateSelfOverride = visuals.BackgroundModulate;
            var backgroundImage = visuals.BackgroundImagePath != null ? _resCache.GetResource<TextureResource>(visuals.BackgroundImagePath) : null;

            if (backgroundImage != null)
            {
                PaperBackground.PanelOverride = new StyleBoxTexture
                {
                    Texture = backgroundImage,
                    TextureScale = visuals.BackgroundScale,
                    Mode = visuals.BackgroundImageTile ? StyleBoxTexture.StretchMode.Tile : StyleBoxTexture.StretchMode.Stretch,
                    PatchMarginLeft = visuals.BackgroundPatchMargin.Left,
                    PatchMarginBottom = visuals.BackgroundPatchMargin.Bottom,
                    PatchMarginRight = visuals.BackgroundPatchMargin.Right,
                    PatchMarginTop = visuals.BackgroundPatchMargin.Top
                };
            }

            WrittenTextLabel.ModulateSelfOverride = visuals.FontAccentColor;
            FillStatus.ModulateSelfOverride = visuals.FontAccentColor;
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.None;
            if (relativeMousePos.Y < DRAG_MARGIN_SIZE) mode |= DragMode.Top;
            else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE) mode |= DragMode.Bottom;
            if (relativeMousePos.X < DRAG_MARGIN_SIZE) mode |= DragMode.Left;
            else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE) mode |= DragMode.Right;

            return mode == DragMode.None ? DragMode.Move : mode;
        }

        private void RunOnSaved()
        {
            SaveButton.Disabled = true;
            OnSaved?.Invoke(Rope.Collapse(Input.TextRope));
        }

        private void UpdateFillState()
        {
            if (MaxInputLength != -1)
            {
                FillStatus.Text = $"{Input.TextLength} / {MaxInputLength}";
                SaveButton.Disabled = Input.TextLength > MaxInputLength;
            }
            else
            {
                FillStatus.Text = "";
                SaveButton.Disabled = false;
            }
        }
    }
}
