using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Sich.BureaucraticComputer.UI;

[GenerateTypedNameReferences]
public sealed partial class BureaucracyComputerWindow : DefaultWindow
{
    public BureaucracyComputerWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
